# find . -name "*.cpp" -not -ipath "*tests*" -not -ipath "*progs*" > corefiles.cmake.t
SET(nice_core_SRC
./image/DeprecatedConverter.cpp
./image/Histogram.cpp
./image/Fourier.cpp
./image/GaussPyramid.cpp
./image/ColorImageAccess.cpp
./image/Convert.cpp
./image/ImageOutputStream.cpp
./image/Morph.cpp
./image/ImageFileListWriter.cpp
./image/ImageAccess.cpp
./image/GrayColorImageCommonImplementation.cpp
./image/FilterT.cpp
./image/GHough.cpp
./image/Algorithms.cpp
./image/ImageT.cpp
./image/Region.cpp
./image/ImageFile.cpp
./image/ImageFileListReader.cpp
./image/MultiChannelImageT.cpp
./image/ImageTools.cpp
./image/ColorImageT.cpp
./image/ImageInputStream.cpp
./image/Filter.cpp
./matlabAccess/MatFileIO.cpp
./imagedisplay/DefaultMainWindow.cpp
./imagedisplay/PolygonDrawer.cpp
./imagedisplay/ArrayPlot.cpp
./imagedisplay/CaptureDialog.cpp
./imagedisplay/ImageDisplaySDL.cpp
./imagedisplay/QtFramework.cpp
./imagedisplay/CaptureWidget.cpp
./imagedisplay/EpipolarGeometryDisplay.cpp
./imagedisplay/ImageDisplayManager.cpp
./imagedisplay/ImageDisplayManagerWidget.cpp
./imagedisplay/SimpleSelector.cpp
./imagedisplay/ImageDisplay.cpp
./basics/bzstream.cpp
./basics/tools.cpp
./basics/BinStreamable.cpp
./basics/FastMath.cpp
./basics/ResourceStatistics.cpp
./basics/Observer.cpp
./basics/FileMgt.cpp
./basics/gzstream.cpp
./basics/Streamable.cpp
./basics/Timer.cpp
./basics/numerictools.cpp
./basics/Exception.cpp
./basics/Log.cpp
./basics/FrameRateCounter.cpp
./basics/StringTools.cpp
./basics/Observable.cpp
./basics/Config.cpp
./basics/FileName.cpp
./basics/stringutils.cpp
./optimization/gradientBased/FirstOrderRasmussen.cpp
./optimization/gradientBased/OptimizationProblemSecond.cpp
./optimization/gradientBased/OptimizationProblemFirst.cpp
./optimization/gradientBased/SecondOrderTrustRegion.cpp
./optimization/gradientBased/OptimizationAlgorithmSecond.cpp
./optimization/gradientBased/TrustRegionBase.cpp
./optimization/gradientBased/OptimizationAlgorithmFirst.cpp
./optimization/gradientBased/FirstOrderTrustRegion.cpp
./optimization/blackbox/SimpleOptProblem.cpp
./optimization/blackbox/CostFunction.cpp
./optimization/blackbox/DownhillSimplexOptimizer.cpp
./optimization/blackbox/SimpleOptimizer.cpp
./optimization/blackbox/Optimizer.cpp
./optimization/blackbox/DimWrapperCostFunction.cpp
./optimization/blackbox/OptLogBase.cpp
./optimization/blackbox/Optimizable.cpp
./algebra/LUDecomposition.cpp
./algebra/ILSPlainGradient.cpp
./algebra/GenericMatrix.cpp
./algebra/GBCDSolver.cpp
./algebra/GMStandard.cpp
./algebra/EigValuesTRLAN.cpp
./algebra/EigValues.cpp
./algebra/ILSSymmLqLanczos.cpp
./algebra/CholeskyRobustAuto.cpp
./algebra/GMSparseVectorMatrix.cpp
./algebra/CholeskyRobust.cpp
./algebra/ILSConjugateGradientsLanczos.cpp
./algebra/IterativeLinearSolver.cpp
./algebra/ILSConjugateGradients.cpp
./algebra/ILSMinResLanczos.cpp
./algebra/DiagonalMatrixApprox.cpp
./vector/Distance.cpp
./vector/VVector.cpp
./vector/Algorithms.cpp
./vector/ippwrapper.cpp
)

set(nice_core_HDR
./image/ColorImageT.h
./image/ImageT.h
./image/Region.h
./image/GrayColorImageCommonImplementationT.h
./image/MultiChannelImageAccess.h
./image/ImageInputStream.h
./image/CrossT.h
./image/Morph.h
./image/BlockImageAccessT.h
./image/ColorImageChannelAccessT.h
./image/RectT.h
./image/ippwrapper.h
./image/LineT.h
./image/RectangleT.h
./image/Drawable.h
./image/GHough.h
./image/DeprecatedConverter.h
./image/ImageOperators.h
./image/Pixel.h
./image/ImageException.h
./image/Fourier.h
./image/PointT.h
./image/CircleT.h
./image/GaussPyramid.h
./image/Histogram.h
./image/ThreeChannelImageT.h
./image/Filter.h
./image/ImageTools.h
./image/ImageFile.h
./image/GrayColorImageCommonImplementation.h
./image/ColorT.h
./image/ImageFileListWriter.h
./image/ImageFileListReader.h
./image/pointerArithmetic.h
./image/ImageOutputStream.h
./image/ColorImageAccess.h
./image/Algorithms.h
./image/MultiChannelImageT.h
./image/TekkotsuLink.h
./image/ImageAccess.h
./image/ImageAccessT.h
./image/CoordT.h
./image/Convert.h
./image/Buffer.h
./image/EllipseT.h
./image/FilterT.h
./matlabAccess/MatFileIO.h
./imagedisplay/DefaultMainWindow.h
./imagedisplay/ImageDisplay.h
./imagedisplay/EpipolarGeometryDisplay.h
./imagedisplay/OverlayColors.h
./imagedisplay/CaptureWidget.h
./imagedisplay/PolygonDrawer.h
./imagedisplay/SimpleSelector.h
./imagedisplay/CaptureDialog.h
./imagedisplay/ImageDisplayManagerWidget.h
./imagedisplay/QtFramework.h
./imagedisplay/ImageDisplayManager.h
./imagedisplay/ArrayPlot.h
./imagedisplay/ImageDisplaySDL.h
./basics/bzstream.h
./basics/RoundToNearest.h
./basics/FrameRateCounter.h
./basics/all.h
./basics/BFSColor.h
./basics/binstream.h
./basics/Observable.h
./basics/CrossplatformDefines.h
./basics/types.h
./basics/Observer.h
./basics/BinStreamable.h
./basics/triplet.h
./basics/deprecated.h
./basics/gzbinstream.h
./basics/Config.h
./basics/stringutils.h
./basics/StringTools.h
./basics/cppunitex.h
./basics/FileMgt.h
./basics/ossettings.h
./basics/gzstream.h
./basics/StructuredMap.h
./basics/ResourceStatistics.h
./basics/quadruplet.h
./basics/numerictools.h
./basics/FileName.h
./basics/FastMath.h
./basics/Timer.h
./basics/tools.h
./basics/Log.h
./basics/vectorio.h
./basics/Persistent.h
./basics/Exception.h
./basics/NonCopyable.h
./basics/Streamable.h
./optimization/gradientBased/OptimizationAlgorithmFirst.h
./optimization/gradientBased/SecondOrderTrustRegion.h
./optimization/gradientBased/OptimizationProblemFirst.h
./optimization/gradientBased/OptimizationAlgorithmSecond.h
./optimization/gradientBased/OptimizationProblemSecond.h
./optimization/gradientBased/FirstOrderRasmussen.h
./optimization/gradientBased/TrustRegionBase.h
./optimization/gradientBased/FirstOrderTrustRegion.h
./optimization/blackbox/CostFunction.h
./optimization/blackbox/SimpleOptimizer.h
./optimization/blackbox/OptLogBase.h
./optimization/blackbox/SimpleOptProblem.h
./optimization/blackbox/Definitions_core_opt.h
./optimization/blackbox/DimWrapperCostFunction.h
./optimization/blackbox/Optimizable.h
./optimization/blackbox/Optimizer.h
./optimization/blackbox/DownhillSimplexOptimizer.h
./iceconversion/image_convertice.h
./iceconversion/convertice.h
./algebra/DiagonalMatrixApprox.h
./algebra/CholeskyRobust.h
./algebra/ILSConjugateGradientsLanczos.h
./algebra/GMStandard.h
./algebra/GenericMatrix.h
./algebra/GBCDSolver.h
./algebra/ILSMinResLanczos.h
./algebra/ILSPlainGradient.h
./algebra/ILSSymmLqLanczos.h
./algebra/CholeskyRobustAuto.h
./algebra/EigValuesTRLAN.h
./algebra/MatrixDecomposition.h
./algebra/PartialGenericMatrix.h
./algebra/LUDecomposition.h
./algebra/GMSparseVectorMatrix.h
./algebra/ILSConjugateGradients.h
./algebra/EigValues.h
./algebra/IterativeLinearSolver.h
./vector/CheckedVectorT.h
./vector/Operators.h
./vector/Distance.h
./vector/MatrixBase.h
./vector/Eigen.h
./vector/VectorBase.h
./vector/ippwrapper.h
./vector/SparseVectorT.h
./vector/cppunitex.h
./vector/VectorT.h
./vector/SVD.h
./vector/Algorithms.h
./vector/CheckedMatrixT.h
./vector/VVector.h
./vector/config.h
./vector/SparseVector.h
./vector/CheckedRowMatrixT.h
./vector/MatrixT.h
./vector/RowMatrixT.h
./image/CircleT.tcc
./image/ImageAccessT.tcc
./image/ippwrapper.tcc
./image/LineT.tcc
./image/Filter.tcc
./image/RectT.tcc
./image/ColorImageT.tcc
./image/GrayColorImageCommonImplementationT.tcc
./image/Buffer.tcc
./image/MultiChannelImageT.tcc
./image/DeprecatedConverter.tcc
./image/FilterT.tcc
./image/EllipseT.tcc
./image/ImageT.tcc
./image/ImageFile.tcc
./image/Pixel.tcc
./image/RectangleT.tcc
./image/PointT.tcc
./image/CrossT.tcc
./image/BlockImageAccessT.tcc
./image/Convert.tcc
./image/Morph.tcc
./image/ColorT.tcc
./image/ImageTools.tcc
./basics/vectorio.tcc
./vector/ippwrapper.tcc
./vector/RowMatrixT.tcc
./vector/VectorT.tcc
./vector/Distance.tcc
./vector/Algorithms.tcc
./vector/Eigen.tcc
./vector/SparseVectorT.tcc
./vector/MatrixT.tcc
)